stages:
  - deploy

push_to_do:
  stage: deploy
  only:
    - master
  script:
    - cp -r * /var/www/.iammiller.com
    - cd /var/www/
    - rm -rf iammiller.com
    - mv .iammiller.com iammiller.com
  tags:
    - iammiller
